<?php

namespace CamiloManrique\LaravelFilter\Tests;

use Orchestra\Testbench\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    protected function setUp(){
        parent::setUp();

        $this->loadMigrationsFrom(['--database' => 'filter-test', '--realpath' => realpath(__DIR__.'/database/migrations'),]);
        $this->withFactories(__DIR__.'/database/factories');
    }

    protected function getEnvironmentSetUp($app)
    {
        parent::getEnvironmentSetUp($app); // TODO: Change the autogenerated stub

        // Setup default database to use sqlite :memory:
        $app['config']->set('database.default', 'filter-test');
        $app['config']->set('database.connections.filter-test', [
            'driver'   => 'sqlite',
            'database' => ':memory:',
//            'host' => 'localhost',
//            'username' => 'root',
//            'password' => 'c31353135',
            'prefix'   => '',
        ]);

        $app['config']->set('filter', require __DIR__.'/../src/config/config.php');
    }

    protected function getPackageProviders($app)
    {
        return [
            \Orchestra\Database\ConsoleServiceProvider::class,
            \CamiloManrique\LaravelFilter\FilterServiceProvider::class
        ];
    }
}

